### ISSUE TITLE
question:Invalid access token!

### ISSUE THREAD

**Issue by Caspar-cao** [kriskbx/gitlab-time-tracker#107]
I according to your steps to install the gitlab-time-tracker.

If I didn't go to configure config, appear this kind of issue :   "Could not resolve issue [num] on http://gitlab.com "

if I change gtt config configure, appear this kind of issue : "Invalid access token!"

I need your help! thanks!

**Comment by yuantao1880** [comment]
i have the same problem，Thanks！

**Comment by yuantao1880** [comment]
BTW，although I use the command like this “gtt sync --url="http://my.url" --token="MYtokengCb1zS", I got the result like this:
Error: Invalid access token!”

**Comment by octoquad** [comment]
You can use `gtt config` then at a minimum you need the following inside your config:

```json
url: https://gitlab.com/api/v4
token: <your-token>
```
Read the [install guide](https://github.com/kriskbx/gitlab-time-tracker/blob/master/documentation.md#installation) and ensure that your private access token allows the `api` scope under https://gitlab.com/profile/personal_access_tokens.

Regarding the  "Could not resolve issue [num] on http://gitlab.com", firstly I see you have http:// instead of https:// and secondly perhaps the issue number doesn't exist under the project you specified e.g. `gtt start my-namespace/my-project 4`. Use `gtt log` to list entries then edit the entry with `gtt edit <id>` and fix up any problems.

Hope that helps!

**Comment by yuantao1880** [comment]
Thanks！




发自网易邮箱大师
On 04/03/2020 23:30, Bruce Pieterse wrote:

You can use gtt config then at a minimum you need the following inside your config:

url: https://gitlab.com/api/v4
token: <your-token>

Read the install guide and ensure that your private access token allows the api scope under https://gitlab.com/profile/personal_access_tokens.

Regarding the "Could not resolve issue [num] on http://gitlab.com", firstly I see you have http:// instead of https:// and secondly perhaps the issue number doesn't exist under the project you specified e.g. gtt start my-namespace/my-project 4. Use gtt log to list entries then edit the entry with gtt edit <id> and fix up any problems.

Hope that helps!

**Comment by cgdobre** [comment]
No news should be good news. Closing issue
