### ISSUE TITLE
Local config does not load global config first

### ISSUE THREAD

**Issue by attiks** [kriskbx/gitlab-time-tracker#12]
This forces the user to repeat `url` and `token` in each project config and introduces the risk that they get pushed to a public repo.

Feature request: when using local config, load global config first.

**Comment by kriskbx** [comment]
I intentionally kept the local config separate from the global one, because I don't wanted to overwrite each setting locally. But you're right, the risk that `url` and `token` parameters are pushed to a public repo by accident is real. I'm willing to merge your PR as it is, but I want to discuss another possibility up first: What about a config option `extend` that allows you to extend the global config if you need to. `true` by default, so it works the same way as your PR but leaves the option for a separate config if the user needs to. When passing a string you can extend a configuration file at the given path. I know that I'm the kinda person that implements a lot of options sacrificing usability and simplicity for more configurability. What do you think about this?

**Comment by attiks** [comment]
Sounds like a great idea

**Comment by kriskbx** [comment]
I just added the option, merged your pull request and released version `1.6.0` which includesthe recent changes. Make sure to [upgrade accordingly](https://github.com/kriskbx/gitlab-time-tracker#updating). Thanks a lot for your contribution, this is very helpful and appreciated. :)
