### ISSUE TITLE
App doesn't work in windows

### ISSUE THREAD

**Issue by drcriado** [kriskbx/gitlab-time-tracker#14]
Hi!

I'm testing your app in windows 10 x64 environment / node v6.11.

Your app was installed without problems using yarn command, but I execute gtt in windows command shell and the app don't answer me. No error messages. Freezed waiting a response.

![gtt](https://user-images.githubusercontent.com/31201886/29507021-a38da5a2-864e-11e7-9058-08edde7033e1.png)

Firewall is off.

Thanks & Regards
P.D.: I'll buy two or three beers for you if this app works!

**Comment by kriskbx** [comment]
In order to run Node.js applications on Windows you have to use the command prompt provided by Node.js instead of cmd.exe. There should be a shortcut in your Startmenu:

<img width="1108" alt="screen shot 2017-08-23 at 12 46 03" src="https://user-images.githubusercontent.com/3148865/29612289-1062bfa6-8801-11e7-8649-903a9726541e.png">

Within the Node.js prompt, install gtt via npm (I'm not sure how yarn and prefixing works on Windows):

```
npm install -g gitlab-time-tracker
```
After the installation is finished it should indeed work as stated in the docs. I tested it on a fresh Windows 10 Creators Update, Node.js 6.11 LTS.

The `gtt config` command didn't work for me. So make sure to run `gtt status` once: this will create the configuration file located here: `C:\Users\YourUserName\.gtt\config.yml`:

<img width="784" alt="screen shot 2017-08-23 at 12 53 21" src="https://user-images.githubusercontent.com/3148865/29612548-14da8234-8802-11e7-9122-c30677ea1214.png">

Open it with the Windows Notepad or the editor of your choice and add your token and url settings.

Make sure to always run gtt inside the Node.js command prompt, it won't work on cmd.exe. Let me know if you still have trouble getting gtt to work.

**Comment by kriskbx** [comment]
Ohh, my bad: I actually found a bug regarding Windows usage in the config method. I just fixed it, make sure to update to Version >= 1.6.1 and try again.

**Comment by drcriado** [comment]
Thanks!!

Check your PayPal account next two days and "push" a beer into your body from Spain!

**Comment by kriskbx** [comment]
You're welcome. Thank you so much for your contribution!
