### ISSUE TITLE
Config userColumns: true ignores members of an added group with master rights

### ISSUE THREAD

**Issue by Felix-IR** [kriskbx/gitlab-time-tracker#25]
Hello, 

First a big THANK YOU for this great project!

I noticed following strange behaviour: 

When using `userColumns: true` in the config or `--user_columns` for creating a report for a specific project , than the issue report ignores users from an added group.

In our case all added group members have a master status or owner. 

All manually added members (Developer or Reporter) are shown in the  issue table.

Command used:
`gtt report "namespace/project" --user_columns --closed --output=table `

Thank you very much!

Best
Felix

**Comment by kriskbx** [comment]
Cheers mate, appreciate it. :) What `--user_columns` actually does is getting all members from the specific project and creating additional columns. I implemented it before even thinking about group-reports. That's why group members that are not members of the specific project don't show up. You can add them manually to the report by adding `time_username` columns for now (replace username with the username of the user you want to add). I will change the behaviour of `--user_columns` to include inherited members from groups too in a future release. Thanks for pointing this out!

**Comment by Felix-IR** [comment]
Thank you very much for your fast answer!

I'm already using the workaround with `time_username` , but when coping with different projects and groups it's getting a bit messy by time ;)

Looking forward to have this fixed in the future!

**Comment by kriskbx** [comment]
I just released version `1.6.9` including a fix for this issue.
