### ISSUE TITLE
Duplicated time records with 'gtt report'

### ISSUE THREAD

**Issue by elboletaire** [kriskbx/gitlab-time-tracker#44]
Some issues appear multiple times, with the exact same time record (and same iid). I discovered this while manually sorting a generated markdown (due to #43). BTW the output type does not affect, outputting it directly to the console (without `--output=markdown`) also duplicates records.

To generate the output I ran this command:

~~~bash
gtt report alvarium/services/programmable-tv socialistes --type=group --subgroups --user=oscar --closed  --hours_per_day=24
~~~

Which outputted me around 130 lines of time records, but looking it further, I can see a lot of time records being duplicated, like this one (iid 9):

![imatge](https://user-images.githubusercontent.com/153305/35385257-04dc4a9e-01c8-11e8-81ab-713c7dcc04fb.png)

And here appears again:

![imatge](https://user-images.githubusercontent.com/153305/35385287-1b57c6a4-01c8-11e8-9613-7be559688f3c.png)

Obviously I checked every duplicated row to ensure I only tracked time once (btw, should not be needed since the date and iid are exactly the same):

![imatge](https://user-images.githubusercontent.com/153305/35385345-45792590-01c8-11e8-9bfa-01ad9f910005.png)

I know the `--closed` flag does not affect, because removing it still shows duplicated results:

![imatge](https://user-images.githubusercontent.com/153305/35385366-5a8b4e2c-01c8-11e8-9a02-db54b8f608c3.png)

**Comment by kriskbx** [comment]
It's very hard to debug something like this which is obviously unique to your set of data. That's why I built a new shiny feature called dumps: Starting with version 1.7.4 you can choose `dump` as an output now and save the results to a file: 

```
gtt report --output=dump --file=~/dump.json
```

The dump contains your config (url and token as well as local paths are removed from it before it get saved to the disk) and every request (only body and response headers, because the rest may contain sensitive data) that your report actually did. You can reuse the dump on another machine without access to the actual GitLab instance by using the new `--from_dump` option:

```
gtt report --from_dump=~/dump.json --output=table
```

This is the same as running API requests in your browser and sending the resulting json over to me. So, in order to debug this. Please run this again with `--output=dump --file=/path/dump.json`, check and replace sensitive information in the resulting json file and send it to me via mail: m at kris dot cool

**Comment by kriskbx** [comment]
If you still experience problems, feel free to reopen this issue. :)

**Comment by wntbrian** [comment]
I have the same issue.
On report with multiple groups, it's duplicate "Selected projects" and finally time records duplicates too.
`docker run --rm -it -v `pwd`:/root/.local/share/.gtt/ kriskbx/gitlab-time-tracker report admins/infra levscience/devops --type=group
🔍  Selected projects: admins/infra/syspass, admins/infra/mariadb, admins/infra/syspass, admins/infra/mariadb, levscience/devops/kubeconfig, admins/infra/syspass, admins/infra/mariadb
🔍  Resolving "admins/infra", "levscience/devops"... ✓
📦  Fetching issues... ✓
📦  Fetching merge requests... ✓
📎  Merging reports... ✓
`
