### ISSUE TITLE
Report fails if the number of issues is too high

### ISSUE THREAD

**Issue by embeddedLance** [kriskbx/gitlab-time-tracker#82]
The report fails if the number of issues in a group or project is too high. I can look into the source code if you point me in the right direction, although I have no experience with NodeJS.

**Comment by kriskbx** [comment]
How many issues are we talking about?

To reproduce and hopefully fix a problem like this I will probably need a [dump with your data](https://github.com/kriskbx/gitlab-time-tracker/blob/master/documentation.md#dumps). Please check it for sensitive information. You can email it to "m at kris dot cool", I will delete it afterwards and never send it to anyone.

**Comment by StanVC** [comment]
For a project with 500 issues the gtt tool is rate-limited during the processing if issues phase of the report command. Gitlab server responds with "Too many requests received. Please try again later."

**Comment by embeddedLance** [comment]
Right! Can we change this rate limit??

**Comment by maks-io** [comment]
I had the same problem with an app, that uses gitlab-time-tracker. Since the app itself was deprecated anyhow and i was not planning to further improve it/use it, the only important thing to me was to get one final report from it, containing all my gitlab issues. My workaround was to simply use the Chrome DevTools, go to the `Network` tab and set `Throttling` to Preset `Slow 3G`. This way the frequency of sent requests is way lower, which leads to bypassing the rate limit. I thought I'd share this because maybe some of you are in a similar situation and just need a quick *workaround*.

**Comment by jdecaron** [comment]
I submitted a pull request that can fix this issue: https://github.com/kriskbx/gitlab-time-tracker/pull/106
